#!/usr/bin/env python3
import os, sys, json
from pathlib import Path
import urllib.request

GITHUB_TOKEN = os.environ.get('GITHUB_TOKEN') or os.environ.get('INPUT_GITHUB_TOKEN')
REPO = os.environ.get('GITHUB_REPOSITORY')
EVENT_PATH = os.environ.get('GITHUB_EVENT_PATH')
RUN_ID = os.environ.get('GITHUB_RUN_ID')

def main():
    if not GITHUB_TOKEN or not REPO or not EVENT_PATH or not RUN_ID:
        print('Missing environment for posting comment. Skipping.'); return
    ev = json.load(open(EVENT_PATH))
    pr_number = None
    if 'pull_request' in ev:
        pr_number = ev['pull_request']['number']
    if not pr_number:
        print('Not a PR event. Skipping comment.'); return

    artifacts_base = f"https://github.com/{REPO}/actions/runs/{RUN_ID}"
    # Read manifest
    manifest_path = Path('artifacts/manifest.json')
    if not manifest_path.exists():
        print('manifest not found, skipping comment'); return
    manifest = json.load(manifest_path.open())

    body_lines = []
    body_lines.append('Automated validation screenshots generated by CI:')
    body_lines.append('')
    for s in manifest.get('screenshots', []):
        body_lines.append(f"- {s['file']}  (filters: errors={s['filter']['errors']}, warnings={s['filter']['warnings']})")
    body_lines.append('')
    body_lines.append(f"Download artifacts and screenshots from the workflow run: {artifacts_base}")
    body_lines.append('')
    # link to generated index.html inside artifacts
    body_lines.append(f"Interactive Review Hub (download artifacts and open): {artifacts_base}")
    body_lines.append('')
    body_lines.append('Short summary:')
    body_lines.append(f"- total_issues: {manifest.get('total_issues')}")
    body_lines.append(f"- errors: {manifest.get('errors')}")
    body_lines.append(f"- warnings: {manifest.get('warnings')}")

    body = '\n'.join(body_lines)

    api_url = f"https://api.github.com/repos/{REPO}/issues/{pr_number}/comments"
    req = urllib.request.Request(api_url, data=json.dumps({'body': body}).encode('utf8'), headers={
        'Authorization': f'Bearer {GITHUB_TOKEN}', 'Accept': 'application/vnd.github.v3+json', 'User-Agent':'hcma-screenshots'
    })
    with urllib.request.urlopen(req) as resp:
        print('Posted PR comment, status', resp.status)

if __name__=='__main__':
    main()
